[package]
name = "ClementineHelper"
version = "0.1.0"
edition = "2021"


[dependencies]

[dependencies.windows-sys]
version = "0.52.0"
features = ["Win32_Foundation", "Win32_System", "Win32_System_LibraryLoader"]